name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.dot"

jobs:
  dot:
    name: Convert .dot files to .svg
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz
        run: sudo apt install -y graphviz
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Convert files
        run: |
          for input_file in $(find . -name '*.dot' -print); do
            output_file=${input_file::-3}svg
            echo "Converting '$input_file' to '$output_file'"
            dot -Tsvg $input_file -o $output_file
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          path: "./**/*.svg"
          retention-days: 1
